In [ ]:
!pip install --upgrade scikit-learn
# 0.22.2.post1 -> 1.0
# import sklearn
# print(sklearn.__version__)

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
## for Kaggle notebook
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

     |████████████████████████████████| 23.2 MB 58.3 MB/s 
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1


In [ ]:
!pwd
## Kaggle
# !ls ../input

## Colab
# !wget 'https://wenzhan1o-my.sharepoint.com/:u:/g/personal/ievtt_kze_me/EagIcOFamPlHgERo56QclZYB20V0UhmNJTVXRpXk_bXqTQ?e=veLGfV&download=1' -O titanic.zip
!wget 'https://bit.ly/3aODbKl' -O titanic.zip
!unzip titanic.zip


/content
--2021-11-03 10:53:23--  https://bit.ly/3aODbKl
Resolving bit.ly (bit.ly)... 67.199.248.10, 67.199.248.11
Connecting to bit.ly (bit.ly)|67.199.248.10|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://wenzhan1o-my.sharepoint.com/:u:/g/personal/ievtt_kze_me/EagIcOFamPlHgERo56QclZYB20V0UhmNJTVXRpXk_bXqTQ?e=veLGfV&download=1 [following]
--2021-11-03 10:53:23--  https://wenzhan1o-my.sharepoint.com/:u:/g/personal/ievtt_kze_me/EagIcOFamPlHgERo56QclZYB20V0UhmNJTVXRpXk_bXqTQ?e=veLGfV&download=1
Resolving wenzhan1o-my.sharepoint.com (wenzhan1o-my.sharepoint.com)... 13.107.136.9, 13.107.138.9
Connecting to wenzhan1o-my.sharepoint.com (wenzhan1o-my.sharepoint.com)|13.107.136.9|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /personal/ievtt_kze_me/Documents/Study/Kaggle/Titanic/titanic.zip [following]
--2021-11-03 10:53:23--  https://wenzhan1o-my.sharepoint.com/personal/ievtt_kze_me/Documents/Study/Kaggle/Titan

In [ ]:
## Kaggle Notebook
# data_path = '../input/titanic/'
## Colab
data_path = './'

train = pd.read_csv(data_path + 'train.csv')
test = pd.read_csv(data_path + 'test.csv')
gender_sub = pd.read_csv(data_path + 'gender_submission.csv')

print(train.head(3))
print(train.info())
print(test.head(3))
print(test.info())


   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S

[3 rows x 12 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), ob

In [ ]:
# 統計量情報
print(train.describe())
print(test.describe())

       PassengerId    Survived      Pclass  ...       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  ...  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642  ...    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071  ...    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000  ...    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000  ...    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000  ...    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000  ...    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000  ...    8.000000    6.000000  512.329200

[8 rows x 7 columns]
       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.3923

In [ ]:
# 欠損データ
def kesson_table(df):
    nul_val = df.isnull().sum()
    kesson_table = pd.concat([nul_val,100 * nul_val / len(df)],axis=1)
    return(kesson_table.rename(columns={0:'欠損数',1:'%'}))

print(kesson_table(train))
print(kesson_table(test))

             欠損数          %
PassengerId    0   0.000000
Survived       0   0.000000
Pclass         0   0.000000
Name           0   0.000000
Sex            0   0.000000
Age          177  19.865320
SibSp          0   0.000000
Parch          0   0.000000
Ticket         0   0.000000
Fare           0   0.000000
Cabin        687  77.104377
Embarked       2   0.224467
             欠損数          %
PassengerId    0   0.000000
Pclass         0   0.000000
Name           0   0.000000
Sex            0   0.000000
Age           86  20.574163
SibSp          0   0.000000
Parch          0   0.000000
Ticket         0   0.000000
Fare           1   0.239234
Cabin        327  78.229665
Embarked       0   0.000000


* PassengerId – 乗客識別ユニークID
* Survived – 生存フラグ（0=死亡、1=生存）
* Pclass – チケットクラス
    * 1 = 上層クラス（お金持ち）
    * 2 = 中級クラス（一般階級）
    * 3 = 下層クラス（労働階級）
* Name – 乗客の名前
* Sex – 性別（male=男性、female＝女性）
* Age – 年齢
* SibSp – タイタニックに同乗している兄弟/配偶者の数
* parch – タイタニックに同乗している親/子供の数
* Ticket – チケット番号
* fare – 料金
* cabin – 客室番号
* Embarked – 出港地（タイタニックへ乗った港）
    * C = Cherbourg
    * Q = Queenstown
    * S = Southampton


## データセットの事前処理

* 欠損データの補完
    * Age：中央値
    * Embarked：最頻値
* 文字データ → カテゴリカルデータ

【Kaggle初心者入門編】タイタニック号で生き残るのは誰？
https://www.codexa.net/kaggle-titanic-beginner/

In [ ]:
import statistics

embarked_na_fill = statistics.mode(train['Embarked'])

# print(pd.unique(train['Sex']))
# > ['male' 'female']

# drop_col_list = ['Name','Ticket','Fare','Cabin','Embarked']
# train.drop(drop_col_list,axis='columns',inplace=True)


def pre_processing(df):
    # 欠損値に設定するデータはtrainで固定するべきでは？参考サイトではtestもtestで中央値を計算しているが
    age_na_fill = df['Age'].median()
    fare_na_fill = df['Fare'].median()

    df['Age'] = df['Age'].fillna(age_na_fill)
    df['Embarked'] = df['Embarked'].fillna(embarked_na_fill)
    df['Fare'] = df['Fare'].fillna(fare_na_fill)
    # df['Sex'][df['Sex']=='male'] = 0
    # df['Sex'][df['Sex']=='female'] = 1
    # df['Embarked'][df['Embarked']=='S'] = 0
    # df['Embarked'][df['Embarked']=='C'] = 1
    # df['Embarked'][df['Embarked']=='Q'] = 2
    df['Sex'].replace({'male':0,'female':1},inplace=True)
    df['Embarked'].replace({'S':0,'C':1,'Q':2},inplace=True)

    return(df)

print(kesson_table(train))

print(train.head(10))

train = pre_processing(train)
test = pre_processing(test)

print(train.head(10))


             欠損数          %
PassengerId    0   0.000000
Survived       0   0.000000
Pclass         0   0.000000
Name           0   0.000000
Sex            0   0.000000
Age          177  19.865320
SibSp          0   0.000000
Parch          0   0.000000
Ticket         0   0.000000
Fare           0   0.000000
Cabin        687  77.104377
Embarked       2   0.224467
   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q
6            7         0       1  ...  51.8625   E46         S
7            8         0       3  ...  21.0750   NaN         S
8            9         1       3  ...  11.1333   NaN         S
9     

### 決定木

In [ ]:
from IPython.display import FileLink
from sklearn import tree
from sklearn.metrics import f1_score

exp_vals = ['Pclass','Sex','Age','Fare']

target = train['Survived'].values
features_one = train[exp_vals].values
print(features_one[:10])

# 決定木の作成
my_tree_one = tree.DecisionTreeClassifier()
my_tree_one = my_tree_one.fit(features_one,target)

train_pred_y = my_tree_one.predict(features_one)
score = f1_score(target, train_pred_y, average="micro")
print('f1　score: ',score)

    
# testの説明変数の値を取得
test_features = test[exp_vals].values

# testの説明変数を使ってmy_tree_oneのモデルで予測
my_prediction = my_tree_one.predict(test_features)

print(my_prediction.shape)
print(my_prediction[:10])

def export_predict(my_prediction,fname):
    # PassengerIdを取得
    PassengerId = np.array(test['PassengerId']).astype(int)
    # my_predistionとPassengerIdをデータフレームに落とし込む
    my_solution = pd.DataFrame(my_prediction,PassengerId,columns=['Survived'])
    # my_tree_one.csvとして書き出し
    my_solution.to_csv(fname,index_label=['PassengerId'])
    FileLink(fname)
    print(my_solution.head(3))

export_predict(my_prediction,'my_tree_one.csv')

# !zip -r file.zip 'my_tree_one.csv' 
    

[[ 3.      0.     22.      7.25  ]
 [ 1.      1.     38.     71.2833]
 [ 3.      1.     26.      7.925 ]
 [ 1.      1.     35.     53.1   ]
 [ 3.      0.     35.      8.05  ]
 [ 3.      0.     28.      8.4583]
 [ 1.      0.     54.     51.8625]
 [ 3.      0.      2.     21.075 ]
 [ 3.      1.     27.     11.1333]
 [ 2.      1.     14.     30.0708]]
f1　score:  0.9775533108866442
(418,)
[0 0 1 1 1 0 0 0 1 0]
     Survived
892         0
893         0
894         1


### 決定木＋7つの説明変数

In [ ]:


def dec_tree(train,test,exp_vals,target_col):

    target = train[target_col].values
    features = train[exp_vals].values
    print(features[:3])

    # 決定木の作成とArgumentの設定
    max_depth = 10
    min_samples_split = 5
    my_dec_tree = tree.DecisionTreeClassifier(max_depth=max_depth
                                                ,min_samples_split=min_samples_split
                                                ,random_state=1)
    my_dec_tree = my_dec_tree.fit(features,target)
    train_pred_y = my_dec_tree.predict(features)

    # print(f"acc: {my_dec_tree.score(train, target_col)}")
    # acc: 0.9416666666666667
    
    score = f1_score(target, train_pred_y, average="micro")
    print('f1　score: ',score)


    # testの説明変数の値を取得
    test_features = test[exp_vals].values

    # testの説明変数を使ってmy_tree_oneのモデルで予測
    my_pred_tree = my_dec_tree.predict(test_features)

    return(my_pred_tree)


exp_vals = ['Pclass','Sex','Age','Fare', 'SibSp','Parch','Embarked']

my_prediction_tree_two = dec_tree(train,test,exp_vals,'Survived')

export_predict(my_prediction_tree_two,'my_tree_two.csv')

print(my_prediction_tree_two.shape)
print(my_prediction_tree_two[:10])


[[ 3.      0.     22.      7.25    1.      0.      0.    ]
 [ 1.      1.     38.     71.2833  1.      0.      1.    ]
 [ 3.      1.     26.      7.925   0.      0.      0.    ]]
f1　score:  0.9057239057239057
     Survived
892         0
893         0
894         0
(418,)
[0 0 0 0 1 0 0 0 1 0]


## OneHotEncoding

https://www.haya-programming.com/entry/2019/08/17/184527


In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Data読み取り～欠損値補完
def read_data():
    train = pd.read_csv(data_path + 'train.csv')
    test = pd.read_csv(data_path + 'test.csv')

    embarked_na_fill = statistics.mode(train['Embarked'])
    # 欠損値に設定するデータはtrainで固定するべきでは？参考サイトではtestもtestで中央値を計算しているが
    age_na_fill = train['Age'].median()
    fare_na_fill = train['Fare'].median()

    train['Age'] = train['Age'].fillna(age_na_fill)
    train['Embarked'] = train['Embarked'].fillna(embarked_na_fill)
    train['Fare'] = train['Fare'].fillna(fare_na_fill)

    test['Age'] = test['Age'].fillna(age_na_fill)
    test['Embarked'] = test['Embarked'].fillna(embarked_na_fill)
    test['Fare'] = test['Fare'].fillna(fare_na_fill)
    return train,test

# 各列のカテゴリ数チェック
for col in train.columns:
    print(col,len(pd.unique(train[col])))

train,test = read_data()

# train2 = train.drop(['PassengerId','Survived','Name','Ticket','Cabin'],axis='columns')
# test2 = test.drop(['PassengerId','Survived','Name','Ticket','Cabin'],axis='columns')

to_ohe_col = ['Sex','Embarked']
# to_ohe_col = ['Pclass','Sex','Embarked']


def change_ohe(df,col):
    ohe = OneHotEncoder(handle_unknown='ignore',sparse=False,dtype=np.float32)
    ohe.fit(pd.DataFrame(df[cols]))
    print(col,ohe.categories_,len(ohe.categories_))
    ohe_array = ohe.transform(pd.DataFrame(df[col]))
    print(ohe_array)
    df_new = df.drop(col,axis='columns').join(pd.DataFrame(ohe_array,columns=ohe.categories_[0]))
    print(df_new)

# ohe fit
def ohe_fit(df,cols):
    ohe = OneHotEncoder(handle_unknown='ignore',sparse=False,dtype=np.float32)
    ohe.fit(pd.DataFrame(df[cols]))
    return(ohe)

# ohe trasform
def ohe_transform(df,cols,ohe):
    ohe_array = ohe.transform(pd.DataFrame(df[cols]))
    print(ohe_array)
    return(df.join(pd.DataFrame(ohe_array,columns=np.concatenate(ohe.categories_))))

ohe = ohe_fit(train,to_ohe_col)
train2 = ohe_transform(train,to_ohe_col,ohe)
test2 = ohe_transform(test,to_ohe_col,ohe)

print(train2)
print(test2)
# train6 = change_ohe(train2,'Embarked')


PassengerId 891
Survived 2
Pclass 3
Name 891
Sex 2
Age 88
SibSp 7
Parch 7
Ticket 681
Fare 248
Cabin 148
Embarked 3
[[0. 1. 0. 0. 1.]
 [1. 0. 1. 0. 0.]
 [1. 0. 0. 0. 1.]
 ...
 [1. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0.]
 [0. 1. 0. 1. 0.]]
[[0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0.]
 ...
 [0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 1. 1. 0. 0.]]
     PassengerId  Survived  Pclass  ...    C    Q    S
0              1         0       3  ...  0.0  0.0  1.0
1              2         1       1  ...  1.0  0.0  0.0
2              3         1       3  ...  0.0  0.0  1.0
3              4         1       1  ...  0.0  0.0  1.0
4              5         0       3  ...  0.0  0.0  1.0
..           ...       ...     ...  ...  ...  ...  ...
886          887         0       2  ...  0.0  0.0  1.0
887          888         1       1  ...  0.0  0.0  1.0
888          889         0       3  ...  0.0  0.0  1.0
889          890         1       1  ...  1.0  0.0  0.0
890          891         0       3  ...  0.0  1.0  0

### 決定木のスコア

In [ ]:
exp_vals = ['Pclass','Age','Fare','SibSp','Parch','female','male','C','Q','S']

my_prediction_tree_3rd = dec_tree(train2,test2,exp_vals,'Survived')

export_predict(my_prediction_tree_two,'my_tree_3rd.csv')

print(my_prediction_tree_two.shape)
print(my_prediction_tree_two[:10])

!ls

[[ 3.     22.      7.25    1.      0.      0.      1.      0.      0.
   1.    ]
 [ 1.     38.     71.2833  1.      0.      1.      0.      1.      0.
   0.    ]
 [ 3.     26.      7.925   0.      0.      1.      0.      0.      0.
   1.    ]]
f1　score:  0.9124579124579124
     Survived
892         0
893         0
894         0
(418,)
[0 0 0 0 1 0 0 0 1 0]
gender_submission.csv  my_tree_one.csv	sample_data  titanic.zip
my_tree_3rd.csv        my_tree_two.csv	test.csv     train.csv


## RandomForest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

train_labels = ['Pclass','Age','Fare','SibSp','Parch','female','male','C','Q','S']

def rand_tree(train,test,train_labels,target_col):

    target = train[target_col].values
    features = train[train_labels].values
    print(features[:3])

    clf = RandomForestClassifier(verbose=True,   # 学習中にログを表示
                              n_jobs=-1,         # 複数のCPUコアを使って並列に学習します。-1は最大値。
                              random_state=2525) # 乱数シード
    clf.fit(features, target)
    train_pred_y = clf.predict(features)

    # print(f"acc: {my_dec_tree.score(train, target_col)}")
    # acc: 0.9416666666666667
    
    score = f1_score(target, train_pred_y, average="micro")
    print('f1　score: ',score)

    print('feature_importances: ',clf.feature_importances_)

    # testの説明変数の値を取得
    test_features = test[exp_vals].values

    # testの説明変数を使ってmy_tree_oneのモデルで予測
    pred = clf.predict(test_features)

    return(pred)

pred = rand_tree(train2,test2,train_labels,'Survived')


[[ 3.     22.      7.25    1.      0.      0.      1.      0.      0.
   1.    ]
 [ 1.     38.     71.2833  1.      0.      1.      0.      1.      0.
   0.    ]
 [ 3.     26.      7.925   0.      0.      1.      0.      0.      0.
   1.    ]]


[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    0.2s finished
[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  46 tasks      | elapsed:    0.0s
[Parallel(n_jobs=2)]: Done 100 out of 100 | elapsed:    0.0s finished


f1　score:  0.9797979797979798
feature_importances:  [0.08916066 0.25136058 0.25018454 0.04797674 0.03797231 0.15155346
 0.13835768 0.01250642 0.00717972 0.01374788]


[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  46 tasks      | elapsed:    0.0s
[Parallel(n_jobs=2)]: Done 100 out of 100 | elapsed:    0.0s finished


## Grid Search
Kaggle(42) - タイタニックをRandom Forestで予測 - グリッドサーチでパラメータの最適化 - PythonとRPAで遊ぶ
https://ailog.site/2021/03/20/2021/0320/


In [ ]:
from sklearn import ensemble, model_selection
from sklearn.model_selection import GridSearchCV

# 試行するパラメータを羅列
params = {
    'criterion'   : ['gini', 'entropy'],
    'n_estimators': [10, 100, 300, 500, 1000, 1500, 2000],
    'max_depth'   : [3, 5, 7, 9, 11]
}
train_x = train2[train_labels].values
train_y = train2['Survived'].values

clf = ensemble.RandomForestClassifier()

grid_search = GridSearchCV(clf, param_grid=params, cv=4)

## 6分くらいかかる
# %time grid_search.fit(train_x, train_y)
# print(grid_search.best_score_)
# print(grid_search.best_params_)

# CPU times: user 6min 38s, sys: 3.32 s, total: 6min 41s
# Wall time: 6min 40s
# 0.8372722498283036
# {'criterion': 'entropy', 'max_depth': 9, 'n_estimators': 300}



## PipeLine

ColumnTransformerで特徴ごとに異なる変換を行うパイプラインを構築する | DevelopersIO  
https://dev.classmethod.jp/articles/how_to_use_columntransformer_sklearn/

scikit-learnのpipelineモジュールで機械学習パイプラインを作る | DevelopersIO  
https://dev.classmethod.jp/articles/create_pipeline_scikit-learn_pipeline/

Python: scikit-learn の Pipeline を使ってみる - CUBE SUGAR CONTAINER  
https://blog.amedama.jp/entry/2018/07/07/223257

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn import set_config
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
# from sklearn.preprocessing import StandardScaler
# from sklearn.experimental import enable_hist_gradient_boosting
# from sklearn.ensemble import HistGradientBoostingClassifier

# Pipeline
# 

df_train = pd.read_csv(data_path + 'train.csv')
df_target = pd.read_csv(data_path + 'test.csv')

# カラムの型を確認
print(df_train)

# <class 'pandas.core.frame.DataFrame'>
# RangeIndex: 891 entries, 0 to 890
# Data columns (total 12 columns):
#  #   Column       Non-Null Count  Dtype  
# ---  ------       --------------  -----  
#  0   PassengerId  891 non-null    int64  
#  1   Survived     891 non-null    int64  
#  2   Pclass       891 non-null    int64  
#  3   Name         891 non-null    object 
#  4   Sex          891 non-null    object 
#  5   Age          714 non-null    float64
#  6   SibSp        891 non-null    int64  
#  7   Parch        891 non-null    int64  
#  8   Ticket       891 non-null    object 
#  9   Fare         891 non-null    float64
#  10  Cabin        204 non-null    object 
#  11  Embarked     889 non-null    object 
# dtypes: float64(2), int64(5), object(5)
# memory usage: 83.7+ KB

## 欠損値の確認
# print(df_train.isnull().sum())

## 特徴と推定対象に分離
X = df_train.drop(['PassengerId','Name','Ticket','Fare','Cabin'], axis=1)
y = df_train['Survived']

X_target = df_target.drop(['PassengerId','Name','Ticket','Fare','Cabin'], axis=1)

## 欠損値の確認
print(X.isnull().sum()[X.isnull().sum() > 0])
# Age         177
# Embarked      2
print(X_target.isnull().sum()[X_target.isnull().sum() > 0])
# Age    86

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# 量的変数の前処理
# numeric_features = ["bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g"]

# numeric_transformer = Pipeline(steps=[
#     ('num_imputer', SimpleImputer(strategy='median')),
#     ('scaler', StandardScaler())])

# カテゴリー変数の前処理1
# Embarked：最頻値で欠損補完/ohe
categorical_transformer1 = Pipeline(steps=[
    ('cat_imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot1', OneHotEncoder(handle_unknown='ignore'))])

# 前処理2
# Sez：One-hotエンコーディング
categorical_transformer2 = Pipeline(steps=[
    ('onehot2', OneHotEncoder(handle_unknown='ignore'))])

# 前処理3
# Age：欠損値補完/One-hotエンコーディング
categorical_transformer3 = Pipeline(steps=[
    ('cat_imputer3', SimpleImputer(strategy='mean')),
    ('onehot3', OneHotEncoder(handle_unknown='ignore'))])

# ColumnTransformerの作成
preprocessor = ColumnTransformer(
    transformers=[
        # ('num', numeric_transformer, numeric_features),
        ('cat1', categorical_transformer1, ['Embarked']),
        ('cat2', categorical_transformer2, ['Sex']),
        ('cat3', categorical_transformer3, ['Age'])])

# 全体のパイプラインの作成
pipe = Pipeline([("preprocessor", preprocessor),  
                 ("RF", RandomForestClassifier())]
                #  ("Classifier", HistGradientBoostingClassifier())]
                )

set_config(display='diagram')   
pipe


     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]
Age         177
Embarked      2
dtype: int64
Age    86
dtype: int64


Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat1',
                                                  Pipeline(steps=[('cat_imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot1',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Embarked']),
                                                 ('cat2',
                                                  Pipeline(steps=[('onehot2',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Sex']),
                                                 ('cat3',
                                                  Pipeline(steps=[('cat_imputer3',
                                                                   SimpleImputer()),
                                                                  ('onehot3',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Age'])])),
                ('RF', RandomForestClassifier())])

In [ ]:
## 訓練データで性能を確認
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)

from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

print('f1 score: ',f1_score(target, train_pred_y, average="micro"))
print('accuracy: ',accuracy_score(y_test, y_pred))


f1 score:  0.9775533108866442
accuracy:  0.7443946188340808


In [ ]:
## 交差検証
from sklearn.model_selection import cross_val_score

scores = cross_val_score(pipe, 
                         X_train, 
                         y_train.values.ravel(), 
                         cv=5,
                         scoring='accuracy')
print(scores)

[0.73134328 0.80597015 0.73134328 0.76691729 0.80451128]


## 交差検証(cross_validate)

cross_val_scoreはもうやめようね。一発で交差検証するにはcross_validateを使う - 静かなる名辞  
https://www.haya-programming.com/entry/2018/03/31/184557  
Python: scikit-learn の cross_validate() 関数で独自の評価指標を計算する - CUBE SUGAR CONTAINER  
https://blog.amedama.jp/entry/sklearn-cv-custom-metric


In [ ]:
from pprint import pprint
from sklearn.model_selection import cross_validate, StratifiedKFold

# モデルを用意する
clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Stratified k-Fold で汎化性能を評価する
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
# 評価する指標
score_funcs = [
    'accuracy',
    'precision',
    'recall',
    'f1',
]
# Cross Validation で検証する
scores = cross_validate(clf, X, y, cv=skf, scoring=score_funcs)
# 得られた指標を出力する
print('accuracy:', scores['test_accuracy'].mean())
print('precision:', scores['test_precision'].mean())
print('recall:', scores['test_recall'].mean())
print('f1:', scores['test_f1'].mean())


gnb = GaussianNB()

scoring = {"p": "precision_macro",
            "r": "recall_macro",
            "f":"f1_macro"}

skf = StratifiedKFold(shuffle=True, random_state=0)
scores = cross_validate(gnb, iris.data, iris.target,
                        cv=skf, scoring=scoring)
pprint(scores)

accuracy: nan
precision: nan
recall: nan
f1: nan


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_forest.py", line 328, in fit
    X, y, multi_output=True, accept_sparse="csc", dtype=DTYPE
  File "/usr/local/lib/python3.7/dist-packages/sklearn/base.py", line 576, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/usr/local/lib/python

NameError: ignored